/******************************************************************************
* Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
* SPDX-License-Identifier: MIT
******************************************************************************/

/*****************************************************************************/
/**
* @file xaie_txn_reserialize_test.c
* @{
*
* This file contains a test case demonstrating the usage of the
* XAie_ReserializeTransaction() API which handles UPDATE_REG commands
* that spill over 16KB boundaries by inserting NOOPs for proper alignment.
*
* Usage: xaie_txn_reserialize_test <txn_binary_file> [output_file]
*
* <pre>
* MODIFICATION HISTORY:
*
* Ver   Who     Date     Changes
* ----- ------  -------- -----------------------------------------------------
* 1.0   User    01/05/2025  Initial creation
* </pre>
*
******************************************************************************/

/***************************** Include Files *********************************/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <xaiengine.h>
#include <xaie_helper.h>

/***************************** Macro Definitions *****************************/
/* IPU requires BASE address to be 0.
 * In ert_mgmt.c code, in aie_ipu_load_pdi() DevInst is initialized with
 * Base address = base_address + (start_col << XAIE_COL_SHIFT)
 * The column offset and base address is added to the address generated by the
 * XPdi_Load().
 */
#define XAIE_BASE_ADDR		0x00000000000
#define XAIE_NUM_ROWS		6
#define XAIE_NUM_COLS		5
#define XAIE_COL_SHIFT		25
#define XAIE_ROW_SHIFT		20
#define XAIE_SHIM_ROW		0
#define XAIE_RES_TILE_ROW_START	1
#define XAIE_RES_TILE_NUM_ROWS	1
#define XAIE_AIE_TILE_ROW_START	2
#define XAIE_AIE_TILE_NUM_ROWS	4

/*****************************************************************************/
/**
*
* This function reads a transaction binary file into a buffer.
*
* @param	Filename: Path to the transaction binary file
* @param	Size: Pointer to store the file size
*
* @return	Pointer to allocated buffer containing file data, NULL on failure
*
******************************************************************************/
static u8* ReadTxnBinaryFile(const char *Filename, size_t *Size)
{
	FILE *fp;
	u8 *Buffer = NULL;
	size_t FileSize;
	size_t BytesRead;

	/* Open the file */
	fp = fopen(Filename, "rb");
	if(fp == NULL) {
		printf("ERROR: Failed to open file '%s'\n", Filename);
		return NULL;
	}

	/* Get file size */
	fseek(fp, 0, SEEK_END);
	FileSize = ftell(fp);
	fseek(fp, 0, SEEK_SET);

	if(FileSize == 0) {
		printf("ERROR: File '%s' is empty\n", Filename);
		fclose(fp);
		return NULL;
	}

	/* Allocate buffer */
	Buffer = (u8*)malloc(FileSize);
	if(Buffer == NULL) {
		printf("ERROR: Failed to allocate %zu bytes for file\n", FileSize);
		fclose(fp);
		return NULL;
	}

	/* Read file content */
	BytesRead = fread(Buffer, 1, FileSize, fp);
	if(BytesRead != FileSize) {
		printf("ERROR: Failed to read file. Expected %zu bytes, got %zu bytes\n",
			FileSize, BytesRead);
		free(Buffer);
		fclose(fp);
		return NULL;
	}

	fclose(fp);
	*Size = FileSize;
	
	printf("Successfully read %zu bytes from '%s'\n", FileSize, Filename);
	return Buffer;
}

/*****************************************************************************/
/**
*
* This function writes a transaction binary to a file.
*
* @param	Filename: Path to the output file
* @param	Buffer: Buffer containing transaction data
* @param	Size: Size of the buffer in bytes
*
* @return	0 on success, -1 on failure
*
******************************************************************************/
static int WriteTxnBinaryFile(const char *Filename, u8 *Buffer, size_t Size)
{
	FILE *fp;
	size_t BytesWritten;

	fp = fopen(Filename, "wb");
	if(fp == NULL) {
		printf("ERROR: Failed to create file '%s'\n", Filename);
		return -1;
	}

	BytesWritten = fwrite(Buffer, 1, Size, fp);
	if(BytesWritten != Size) {
		printf("ERROR: Failed to write file. Expected %zu bytes, wrote %zu bytes\n",
			Size, BytesWritten);
		fclose(fp);
		return -1;
	}

	fclose(fp);
	printf("Successfully wrote %zu bytes to '%s'\n", Size, Filename);
	return 0;
}

/*****************************************************************************/
/**
*
* This function demonstrates the usage of XAie_ReserializeTransaction() API
* on a given transaction binary file.
*
* @param	DevInst: Device Instance
* @param	TxnFile: Path to input transaction binary file
* @param	OutputFile: Path to output file (optional, can be NULL)
*
* @return	0 on success, error code on failure.
*
******************************************************************************/
static int XAie_TxnReserializeTest(XAie_DevInst *DevInst, const char *TxnFile,
	const char *OutputFile)
{
	u8 *TxnPtr = NULL;
	u8 *ReserTxnPtr = NULL;
	bool NeedReser;
	XAie_TxnHeader *TxnHdr;
	XAie_TxnHeader *ReserTxnHdr;
	size_t FileSize;
	int RetVal = 0;
	
	printf("\n========================================\n");
	printf("Transaction Reserialization Test\n");
	printf("========================================\n\n");

	/*
	 * Read the transaction binary file
	 */
	printf("Step 1: Reading transaction binary file...\n");
	TxnPtr = ReadTxnBinaryFile(TxnFile, &FileSize);
	if(TxnPtr == NULL) {
		return -1;
	}

	/* Validate the transaction header */
	if(FileSize < sizeof(XAie_TxnHeader)) {
		printf("ERROR: File too small to contain a valid transaction header\n");
		printf("  File size: %zu bytes, Header size: %zu bytes\n",
			FileSize, sizeof(XAie_TxnHeader));
		free(TxnPtr);
		return -1;
	}

	TxnHdr = (XAie_TxnHeader *)TxnPtr;
	printf("\nOriginal Transaction Header:\n");
	printf("  - Version: %u.%u\n", TxnHdr->Major, TxnHdr->Minor);
	printf("  - Device Generation: %u\n", TxnHdr->DevGen);
	printf("  - Grid Size: %ux%u tiles (%u mem tile rows)\n", 
		TxnHdr->NumCols, TxnHdr->NumRows, TxnHdr->NumMemTileRows);
	printf("  - Number of Operations: %u\n", TxnHdr->NumOps);
	printf("  - Total Size: %u bytes\n", TxnHdr->TxnSize);

	/* Validate transaction size matches file size */
	if(TxnHdr->TxnSize != FileSize) {
		printf("WARNING: Transaction size mismatch!\n");
		printf("  Header TxnSize: %u bytes, File size: %zu bytes\n",
			TxnHdr->TxnSize, FileSize);
	}
	printf("\n");

	/*
	 * Call XAie_ReserializeTransaction() API
	 */
	printf("Step 2: Calling XAie_ReserializeTransaction()...\n");
	NeedReser = XAie_ReserializeTransaction(DevInst, TxnPtr, &ReserTxnPtr);
	
	if(NeedReser) {
		printf("\n*** RESERIALIZATION PERFORMED ***\n\n");
		printf("Result: Transaction had UPDATE_REG commands crossing 16KB boundaries\n");
		
		if(ReserTxnPtr == NULL) {
			printf("ERROR: Reserialization indicated but buffer is NULL\n");
			RetVal = -1;
			goto cleanup;
		}
		
		ReserTxnHdr = (XAie_TxnHeader *)ReserTxnPtr;
		printf("\nReserialized Transaction Header:\n");
		printf("  - Version: %u.%u\n", ReserTxnHdr->Major, ReserTxnHdr->Minor);
		printf("  - Device Generation: %u\n", ReserTxnHdr->DevGen);
		printf("  - Grid Size: %ux%u tiles (%u mem tile rows)\n", 
			ReserTxnHdr->NumCols, ReserTxnHdr->NumRows, ReserTxnHdr->NumMemTileRows);
		printf("  - Number of Operations: %u\n", ReserTxnHdr->NumOps);
		printf("  - Total Size: %u bytes\n", ReserTxnHdr->TxnSize);

		printf("\nComparison:\n");
		printf("  - Operations Added: %u (NOOPs for alignment)\n", 
			ReserTxnHdr->NumOps - TxnHdr->NumOps);
		printf("  - Size Increase: %u bytes (%u -> %u)\n", 
			ReserTxnHdr->TxnSize - TxnHdr->TxnSize,
			TxnHdr->TxnSize, ReserTxnHdr->TxnSize);
		printf("  - Size Increase: %.2f%%\n",
			((float)(ReserTxnHdr->TxnSize - TxnHdr->TxnSize) / TxnHdr->TxnSize) * 100.0);

		/* Write output file if specified */
		if(OutputFile != NULL) {
			printf("\nStep 3: Writing reserialized transaction to file...\n");
			if(WriteTxnBinaryFile(OutputFile, ReserTxnPtr, ReserTxnHdr->TxnSize) == 0) {
				printf("  SUCCESS: Reserialized transaction saved to '%s'\n", OutputFile);
			} else {
				printf("  ERROR: Failed to write output file\n");
				RetVal = -1;
			}
		}
		
		printf("\n*** Use the reserialized buffer for execution ***\n");
		
	} else {
		printf("\n*** NO RESERIALIZATION NEEDED ***\n\n");
		printf("Result: Transaction does not have UPDATE_REG commands crossing 16KB boundaries\n");
		printf("  The original transaction can be used directly without modification\n");

		if(OutputFile != NULL) {
			printf("\nNote: Output file not written (no reserialization performed)\n");
		}
	}
	printf("\n");

	printf("========================================\n");
	printf("Test Completed Successfully!\n");
	printf("========================================\n\n");

cleanup:
	/* Clean up allocated buffers */
	if(ReserTxnPtr != NULL) {
		free(ReserTxnPtr);
	}
	if(TxnPtr != NULL) {
		free(TxnPtr);
	}

	return RetVal;
}

/*****************************************************************************/
/**
*
* This is the main entry function for the test case.
*
* @param	argc: Number of command line arguments
* @param	argv: Command line arguments
*
* @return	0 on success, error code on failure.
*
******************************************************************************/
int main(int argc, char *argv[])
{
	AieRC RC;
	XAie_SetupConfig(ConfigPtr, XAIE_DEV_GEN_AIE2IPU, XAIE_BASE_ADDR,
			XAIE_COL_SHIFT, XAIE_ROW_SHIFT,
			XAIE_NUM_COLS, XAIE_NUM_ROWS, XAIE_SHIM_ROW,
			XAIE_RES_TILE_ROW_START, XAIE_RES_TILE_NUM_ROWS,
			XAIE_AIE_TILE_ROW_START, XAIE_AIE_TILE_NUM_ROWS);
	XAie_InstDeclare(DevInst, &ConfigPtr);
	const char *InputFile;
	const char *OutputFile = NULL;

	printf("\n");
	printf("***********************************************************\n");
	printf("*  AIE Transaction Reserialization API Test               *\n");
	printf("***********************************************************\n\n");

	/* Parse command line arguments */
	if(argc < 2) {
		printf("Usage: %s <txn_binary_file> [output_file]\n\n", argv[0]);
		printf("Arguments:\n");
		printf("  txn_binary_file  - Input transaction binary file\n");
		printf("  output_file      - (Optional) Output file for reserialized transaction\n");
		printf("\nExample:\n");
		printf("  %s input.txn output.txn\n\n", argv[0]);
		return -1;
	}

	InputFile = argv[1];
	if(argc >= 3) {
		OutputFile = argv[2];
	}

	printf("Configuration:\n");
	printf("  Input file:  %s\n", InputFile);
	if(OutputFile != NULL) {
		printf("  Output file: %s\n", OutputFile);
	} else {
		printf("  Output file: <not specified>\n");
	}
	printf("\n");

	/*
	 * Initialize the device instance
	 */
	printf("Initializing AIE Device Instance...\n");

	RC = XAie_SetupPartitionConfig(&DevInst, XAIE_BASE_ADDR, 1, 1);
	if(RC != XAIE_OK) {
		printf("ERROR: Failed to configure partition (RC=%d)\n", RC);
		return -1;
	}

	RC = XAie_CfgInitialize(&DevInst, &ConfigPtr);
	if(RC != XAIE_OK) {
		printf("ERROR: Failed to initialize device instance (RC=%d)\n", RC);
		return -1;
	}

	RC = XAie_PmRequestTiles(&DevInst, NULL, 0);
	if(RC != XAIE_OK) {
		printf("ERROR: Failed to request tiles (RC=%d)\n", RC);
		return -1;
	}

	RC = XAie_PartitionInitialize(&DevInst, NULL);
	if(RC != XAIE_OK) {
		printf("ERROR: Partition initialization failed (RC=%d)\n", RC);
		return -1;
	}

	printf("Device instance initialized successfully\n");

	/*
	 * Run the reserialization test
	 */
	RC = XAie_TxnReserializeTest(&DevInst, InputFile, OutputFile);
	if(RC != 0) {
		printf("\nTEST FAILED (RC=%d)\n", RC);
		XAie_Finish(&DevInst);
		return -1;
	}

	/*
	 * Cleanup
	 */
	printf("Cleaning up device instance...\n");
	XAie_Finish(&DevInst);
	printf("Cleanup complete\n\n");

	printf("***********************************************************\n");
	printf("*  ALL TESTS PASSED                                       *\n");
	printf("***********************************************************\n\n");

	return 0;
}

/** @} */
