// Copyright(C) 2020 - 2021 by Xilinx, Inc. All rights reserved.
// SPDX-License-Identifier: MIT

#ifndef HW_CONFIG_H
#define HW_CONFIG_H

#include <xaiengine.h>

#if AIE_GEN == XAIE_DEV_GEN_AIEML
#define HW_GEN XAIE_DEV_GEN_AIEML
#define XAIE_NUM_ROWS            11
#define XAIE_NUM_COLS            38
#define XAIE_BASE_ADDR 0x20000000000
#define XAIE_COL_SHIFT 25
#define XAIE_ROW_SHIFT 20
#define XAIE_SHIM_ROW 0
#define XAIE_MEM_TILE_ROW_START 1
#define XAIE_MEM_TILE_NUM_ROWS 2
#define XAIE_AIE_TILE_ROW_START 3
#define XAIE_AIE_TILE_NUM_ROWS 8

#elif AIE_GEN == XAIE_DEV_GEN_AIE
#define HW_GEN XAIE_DEV_GEN_AIE
#define XAIE_NUM_ROWS            9
#define XAIE_NUM_COLS            50
#define XAIE_BASE_ADDR 0x20000000000
#define XAIE_COL_SHIFT 23
#define XAIE_ROW_SHIFT 18
#define XAIE_SHIM_ROW 0
#define XAIE_MEM_TILE_ROW_START 0
#define XAIE_MEM_TILE_NUM_ROWS 0
#define XAIE_AIE_TILE_ROW_START 1
#define XAIE_AIE_TILE_NUM_ROWS 8

#elif AIE_GEN == XAIE_DEV_GEN_AIE2IPU
#define HW_GEN XAIE_DEV_GEN_AIE2IPU
#define XAIE_NUM_ROWS            6
#define XAIE_NUM_COLS            5
#define XAIE_BASE_ADDR 0x00000000000
#define XAIE_COL_SHIFT 25
#define XAIE_ROW_SHIFT 20
#define XAIE_SHIM_ROW 0
#define XAIE_MEM_TILE_ROW_START 1
#define XAIE_MEM_TILE_NUM_ROWS 1
#define XAIE_AIE_TILE_ROW_START 2
#define XAIE_AIE_TILE_NUM_ROWS 4

#elif AIE_GEN == XAIE_DEV_GEN_AIE2P
#define HW_GEN XAIE_DEV_GEN_AIE2P
#define XAIE_NUM_ROWS            6
#define XAIE_NUM_COLS            4
#define XAIE_BASE_ADDR 0x00000000000
#define XAIE_COL_SHIFT 25
#define XAIE_ROW_SHIFT 20
#define XAIE_SHIM_ROW 0
#define XAIE_MEM_TILE_ROW_START 1
#define XAIE_MEM_TILE_NUM_ROWS 1
#define XAIE_AIE_TILE_ROW_START 2
#define XAIE_AIE_TILE_NUM_ROWS 4

#elif AIE_GEN == XAIE_DEV_GEN_AIE2PS
#define HW_GEN XAIE_DEV_GEN_AIE2PS
#define XAIE_NUM_ROWS            8
#define XAIE_NUM_COLS            20
#define XAIE_BASE_ADDR 0x22000000000
#define XAIE_COL_SHIFT 25
#define XAIE_ROW_SHIFT 20
#define XAIE_SHIM_ROW 0
#define XAIE_MEM_TILE_ROW_START 1
#define XAIE_MEM_TILE_NUM_ROWS 2
#define XAIE_AIE_TILE_ROW_START 3
#define XAIE_AIE_TILE_NUM_ROWS 5

#elif AIE_GEN == XAIE_DEV_GEN_AIE2P_STRIX_A0
#define HW_GEN XAIE_DEV_GEN_AIE2P_STRIX_A0
#define XAIE_NUM_ROWS            6
#define XAIE_NUM_COLS            4
#define XAIE_BASE_ADDR 0x00000000000
#define XAIE_COL_SHIFT 25
#define XAIE_ROW_SHIFT 20
#define XAIE_SHIM_ROW 0
#define XAIE_MEM_TILE_ROW_START 1
#define XAIE_MEM_TILE_NUM_ROWS 1
#define XAIE_AIE_TILE_ROW_START 2
#define XAIE_AIE_TILE_NUM_ROWS 4

#elif AIE_GEN == XAIE_DEV_GEN_AIE2P_STRIX_B0
#define HW_GEN XAIE_DEV_GEN_AIE2P_STRIX_B0
#define XAIE_NUM_ROWS            6
#define XAIE_NUM_COLS            8
#define XAIE_BASE_ADDR 0x00000000000
#define XAIE_COL_SHIFT 25
#define XAIE_ROW_SHIFT 20
#define XAIE_SHIM_ROW 0
#define XAIE_MEM_TILE_ROW_START 1
#define XAIE_MEM_TILE_NUM_ROWS 1
#define XAIE_AIE_TILE_ROW_START 2
#define XAIE_AIE_TILE_NUM_ROWS 4

#endif

#endif /* HW_CONFIG_H */
